version: "3.9"

services:
  db:
    image: postgres:15
    container_name: casino38-db
    restart: always
    environment:
      POSTGRES_USER: casino_user
      POSTGRES_PASSWORD: casino_pass
      POSTGRES_DB: casino38
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: casino38-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
